<?php
/** 返回一些默认的ebay站点
 * Created by PhpStorm.
 * User: llf
 * Date: 2016-08-25
 * Time: 15:17
 */
return [
    'site_name_id' => [
        'US' => 0,
        'Canada' => 2,
        'UK' => 3,
        'Germany' => 77,
        'Australia' => 15,
        'France' => 71,
        'eBayMotors' => 100,
        'Italy' => 101,
        'Netherlands' => 146,
        'Spain' => 186,
        'India' => 203,
        'HongKong' => 201,
        'Singapore' => 216,
        'Malaysia' => 207,
        'Philippines' => 211,
        'CanadaFrench' => 210,
        'Poland' => 212,
        'Belgium_Dutch' => 123,
        'Belgium_French' => 23,
        'Austria' => 16,
        'Switzerland' => 193,
        'Ireland' => 205,
    ],
    'unpaid' => [
        2, 3, 4, 5
    ],
    'unpaid_day' => [
        'Days_30' => 30,
        'Days_180' => 180,
        'Days_360' => 360
    ],
    'policy' => [
        4, 5, 6, 7
    ],
    'policy_day' => [
        'Days_30' => 30,
        'Days_180' => 180
    ],
    'feedback' => [
        -1, -2, -3
    ],
    'item_count' => [
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 25, 50, 75, 100
    ],
    'item_count_feedback' => [
        5, 4, 3, 2, 1, 0
    ],
    'warehouse' => [
        1 => '中国仓',
        2 => '美国仓',
        3 => '德国仓'
    ],
    'currency' => [
        'USD', 'CAD', 'GBP', 'EUR', 'AUD'
    ],
    'status' => [
        '0' => '草稿',
        '1' => '待发布',
        '2' => '在线',
        '3' => '已下线',
    ],
    'ebay_country' => [
        'Worldwide' => 'Worldwide',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AG' => 'Antigua and Barbuda',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'BH' => 'Bahrain',
        'BE' => 'Belgium',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BA' => 'Bosnia and Herzegovina',
        'BW' => 'Botswana',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'MM' => 'Burma',
        'BI' => 'Burundi',
        'CM' => 'Cameroon',
        'KY' => 'Cayman Islands',
        'CL' => 'Chile',
        'KM' => 'Comoros',
        'CG' => 'Congo, Republic of the',
        'CK' => 'Cook Islands',
        'CI' => 'Cote d Ivoire (Ivory Coast)',
        'HR' => 'Croatia, Democratic Republic o',
        'CZ' => 'Czech Republic',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'GQ' => 'Equatorial Guinea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GN' => 'Guinea',
        'HT' => 'Haiti',
        'HN' => 'Honduras',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IL' => 'Israel',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KI' => 'Kiribati',
        'KP' => 'Korea, North',
        'KW' => 'Kuwait',
        'LS' => 'Lesotho',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'MO' => 'Macau',
        'MG' => 'Madagascar',
        'ML' => 'Mali',
        'MH' => 'Marshall Islands',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MN' => 'Mongolia',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'NR' => 'Nauru',
        'AN' => 'Netherlands Antilles',
        'NC' => 'New Caledonia',
        'NE' => 'Niger',
        'PK' => 'Pakistan',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'SH' => 'Saint Helena',
        'KN' => 'Saint Kitts-Nevis',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ES' => 'Spain',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SE' => 'Sweden',
        'SY' => 'Syria',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TT' => 'Trinidad and Tobago',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'UY' => 'Uruguay',
        'VU' => 'Vanuatu',
        'VA' => 'Vatican City State',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'VI' => 'Virgin Islands (U.S.)',
        'EH' => 'Western Sahara',
        'WS' => 'Western Samoa',
        'YE' => 'Yemen',
        'ZW' => 'Zimbabwe',
        'AO' => 'Angola',
        'AA' => 'APO/FPO',
        'JP' => 'Japan',
        'RE' => 'Réunion',
        'FM' => 'Micronesia',
        'AD' => 'Andorra',
        'AM' => 'Armenia',
        'BS' => 'Bahamas',
        'BY' => 'Belarus',
        'BT' => 'Bhutan',
        'VG' => 'British Virgin Islands',
        'KH' => 'Cambodia',
        'CF' => 'Central African Republic',
        'CD' => 'Congo, Democratic Republic of',
        'CY' => 'Cyprus',
        'DO' => 'Dominican Republic',
        'ER' => 'Eritrea',
        'FJ' => 'Fiji',
        'GA' => 'Gabon Republic',
        'GI' => 'Gibraltar',
        'GU' => 'Guam',
        'GW' => 'Guinea-Bissau',
        'HU' => 'Hungary',
        'IR' => 'Iran',
        'KE' => 'Kenya Coast Republic',
        'LA' => 'Laos',
        'LR' => 'Liberia',
        'LU' => 'Luxembourg',
        'MY' => 'Malaysia',
        'MQ' => 'Martinique',
        'MX' => 'Mexico',
        'MS' => 'Montserrat',
        'NP' => 'Nepal',
        'NZ' => 'New Zealand',
        'NO' => 'Norway',
        'PH' => 'Philippines',
        'RO' => 'Romania',
        'LC' => 'Saint Lucia',
        'SN' => 'Senegal',
        'SK' => 'Slovakia',
        'ZA' => 'South Africa',
        'SJ' => 'Svalbard',
        'TG' => 'Togo',
        'TV' => 'Tuvalu',
        'AF' => 'Afghanistan',
        'AZ' => 'Azerbaijan Republic',
        'BN' => 'Brunei Darussalam',
        'CO' => 'Colombia',
        'DK' => 'Denmark',
        'FI' => 'Finland',
        'GD' => 'Grenada',
        'HK' => 'Hong Kong',
        'LV' => 'Latvia',
        'MW' => 'Malawi',
        'MC' => 'Monaco',
        'NI' => 'Nicaragua',
        'PM' => 'Saint Pierre and Miquelon',
        'SZ' => 'Swaziland',
        'TR' => 'Turkey',
        'AI' => 'Anguilla',
        'BO' => 'Bolivia',
        'CN' => 'China',
        'EG' => 'Egypt',
        'GH' => 'Ghana',
        'IQ' => 'Iraq',
        'LB' => 'Lebanon, South',
        'MD' => 'Moldova',
        'SM' => 'San Marino',
        'TW' => 'Taiwan',
        'OM' => 'Oman',
        'RU' => 'Russian Federation',
        'TO' => 'Tonga',
        'SG' => 'Singapore',
        'AR' => 'Argentina',
        'TD' => 'Chad',
        'PF' => 'French Polynesia',
        'KG' => 'Kyrgyzstan',
        'NU' => 'Niue',
        'SI' => 'Slovenia',
        'BZ' => 'Belize',
        'SV' => 'El Salvador',
        'GT' => 'Guatemala',
        'IT' => 'Italy',
        'MV' => 'Maldives',
        'NL' => 'Netherlands',
        'TH' => 'Thailand',
        'AS' => 'American Samoa',
        'BD' => 'Bangladesh',
        'BR' => 'Brazil',
        'CV' => 'Cape Verde Islands',
        'CR' => 'Costa Rica',
        'EC' => 'Ecuador',
        'FK' => 'Falkland Islands (Islas Makvin',
        'GY' => 'Guyana',
        'IE' => 'Ireland',
        'KR' => 'Korea, South',
        'MK' => 'Macedonia',
        'MR' => 'Mauritania',
        'NA' => 'Namibia',
        'NG' => 'Nigeria',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'VC' => 'Saint Vincent and the Grenadin',
        'SA' => 'Saudi Arabia',
        'LK' => 'Sri Lanka',
        'CH' => 'Switzerland',
        'TN' => 'Tunisia',
        'TC' => 'Turks and Caicos Islands',
        'UZ' => 'Uzbekistan',
        'WF' => 'Wallis and Futuna',
        'ZM' => 'Zambia',
        'BB' => 'Barbados',
        'CA' => 'Canada',
        'CU' => 'Cuba',
        'GP' => 'Guadeloupe',
        'JM' => 'Jamaica',
        'MT' => 'Malta',
        'PA' => 'Panama',
        'RW' => 'Rwanda',
        'TM' => 'Turkmenistan',
        'US' => 'United States',
        'PW' => 'Palau',
        'ME' => 'Montenegro',
        'RS' => 'Serbia'
    ],
    //对应站点和中国的小时差
    'site_time' => [
        0 => -12,
        2 => -13,
        3 => 2,
        77 => 2,
        15 => 10,
        71 => 2,
        101 => 2,
        186 => 2,
    ],

    //
    'default_account' => 'pandamotos2012',

    'init_currency' => [
        0 => 'USD',
        2 => 'CAD',
        3 => 'GBP',
        77 => 'EUR',
        15 => 'AUD',
        71 => 'EUR',
        100 => 'USD',
        101 => 'EUR',
        146 => 'EUR',
        186 => 'EUR',
        203 => 'INR',
        201 => 'HKD',
        216 => 'SGD',
        207 => 'MYR',
        211 => 'PHP',
        210 => 'CAD',
        212 => 'PLN',
        123 => 'EUR',
        23 => 'EUR',
        16 => 'EUR',
        193 => 'CHF',
        205 => 'EUR'
    ]
];