<?php
return [

    'channel_id' => '渠道',
    'channel_account_id' => '渠道账号',
    'order_id' => '订单号',
    'warehouse_id' => '仓库',
    'logistics_id' => '物流方式',
    'shipper_id' => '发货人',
    'type' => '类型',
    'cost' => '运费',
    'weight' => '系统重量',
    'actual_weight' => '复检重量',
    'tracking_no' => '追踪号(挂号码)',
    'tracking_link' => '追踪链接',
    'is_mark' => '是否备注',
    'is_upload' => '是否上传',
    'email' => 'email',
    'shipping_firstname' => '收货人姓名',
    'shipping_address' => '收货人地址',
    'shipping_address1' => '收货人地址1',
    'shipping_city' => '收货城市',
    'shipping_state' => '收货省市(自治州)',
    'shipping_zipcode' => '收货邮编',
    'shipping_phone' => '收货电话',
    'remark' => '备注',
    'printed_at' => '打印时间',
    'delieved_at' => '妥投时间',
    'status' => '状态',

    'id' => '包裹id',
    'shipping_country' => '收货人国家',
    'shipping_cn_country' => '收货人国家中文名',
    'shipping_enall_country' => '收货人国家英文全称',
    'shipped_at' => '发货时间',
    'shipping_type' => '发货方式',
    'amount' => "包裹金额",
    'buyer_id' => '买家id',
    'currency' => '买家币种',
    'expected_logistics_fee' => '预估运费',
    'double_check' => '是否复检',
    'sku_en' => 'sku申报英文名',
    'sku_cn' => 'sku申报中文名',
    'sku_quantity' => 'sku数量',
    'sku_cost' => 'sku单价',
    'sku_declared_value' => 'sku申报价值',
    'sku_all_quantity' => 'sku物品总数',
    'sku_and_quantity' => 'sku和数量组合',
];