<?php
    return [
        'stock.create',
        'stock.importByExcel',
        'stock.edit',
        'stockAdjustment.create',
        'stockAdjustment.edit',
        'stockAdjustment.check',
        'stockAllotment.create',
        'stockAllotment.edit',
        'allotment.checkout',
        'allotment.check',
        'allotment.checkform',
        'pickList.edit',
        'pickList.package',
        'pickList.inbox',
        'pickList.createPick',
        'package.shippingStatistics',
    ];